kind: ReplicationController
id: notification-controller
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: notification
    version: v1
  podTemplate:
    labels:
      name : notification
      version: v1
    desiredState:
      manifest:
        containers:
          - name: notification
            image: clemble/notification:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10002
                hostPort: 10002
                protocol: TCP
            labels:
              name : notification
              version: v1
